AWSTemplateFormatVersion: '2010-09-09'
Description: Stack LDAP Server

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Selecciona una clau SSH existent

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  RouteToInternet:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  LDAPServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: LDAP Server SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22,  ToPort: 22,  CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 80,  ToPort: 80,  CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 389, ToPort: 389, CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 636, ToPort: 636, CidrIp: 0.0.0.0/0 }

  LDAPServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fa3fe0fa7920f68e
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: [!Ref LDAPServerSG]
      Tags:
        - Key: Name
          Value: LDAP Server

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe

          yum update -y

          # Instal·lar git i ansible
          yum install -y git ansible

          # Executar el playbook des del repositori
          sudo ansible-pull \
            -U https://github.com/xgiralt64/Practica3-AMSA-LDAP.git \
            -d /opt/ansible \
            -i localhost \
            server.yml > /var/log/ansible-pull.log 2>&1




Outputs:
  LDAPServerPublicIP:
    Description: IP pública
    Value: !GetAtt LDAPServerInstance.PublicIp

  ExportVPCId:
    Value: !Ref VPC
    Export: { Name: LDAP-VPC-ID }

  ExportSubnetId:
    Value: !Ref PublicSubnet
    Export: { Name: LDAP-SUBNET-ID }

  ExportServerSG:
    Value: !Ref LDAPServerSG
    Export: { Name: LDAP-SERVER-SG }
