---
- name: Configuració Server
  become: yes
  hosts: localhost
  tasks:
    - name: Actualitzar repositoris
      dnf:
        name: "*"
        state: latest

    - name: Instalar paquets necessaris
      dnf:
          name:
            - cyrus-sasl-devel
            - make
            - libtool
            - autoconf
            - libtool-ltdl-devel
            - openssl-devel
            - libdb-devel
            - tar
            - gcc
            - perl
            - perl-devel
            - wget
            - vim
          state: present
          update_cache: yes
    
    - name: Instalar OpenLDAP
      become: yes
      vars:
        openldap_ver: "2.6.3"
      shell: |
        wget ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-{{ openldap_ver }}.tgz
        tar xzf openldap-{{ openldap_ver }}.tgz
        cd openldap-{{ openldap_ver }}
        ./configure --prefix=/usr --sysconfdir=/etc --disable-static \
          --enable-debug --with-tls=openssl --with-cyrus-sasl --enable-dynamic \
          --enable-crypt --enable-spasswd --enable-slapd --enable-modules \
          --enable-rlookups --disable-sql --enable-ppolicy --enable-syslog
        make depend
        make
        cd contrib/slapd-modules/passwd/sha2
        make
        cd ../../../..
        make install
        cd contrib/slapd-modules/passwd/sha2
        make install
      args:
        chdir: /tmp


